---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - access.breakglass.io
  resources:
  - accessprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - access.breakglass.io
  resources:
  - accessprofiles/status
  - breakglasssessions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - access.breakglass.io
  resources:
  - breakglasssessions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.breakglass.io
  resources:
  - breakglasssessions/finalizers
  verbs:
  - update
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - breakglass-pod-observer
  resources:
  - clusterroles
  verbs:
  - bind
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - watch
