## Append samples of your project ##
resources:
- rbac_breakglass_pod_observer_clusterrole.yaml
- access_v1alpha1_breakglasssession.yaml
- access_v1alpha1_accessprofile.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
